type TicketShop @entity(immutable: true) {
  id: Bytes!
  timestamp_s: BigInt!
  ownerAddress: Bytes!
  ticketShopAddress: Bytes!
  erc20TokenAddress: Bytes!
  paymasterAddress: Bytes!
  nftAddress: Bytes!
  totalTickets: BigInt!
  metadata: TicketMetadata!
}

type TicketMetadata @entity(immutable: true) {
  id: Bytes!
  name: String!
  description: String!
  uri: String!
  dates: [BigInt!]!
  location_uri: String!
  location_name: String!
  pricing: TicketPricing!
}

type TicketPricing @entity(immutable: true) {
  id: Bytes!
  name: [String!]!
  description: [String!]!
  price: [BigInt!]!
  soldTickets: [BigInt!]!
  totalTickets: [BigInt!]!
}

# type TicketLocation @entity(immutable: true) {
#   id: Bytes!
#   name: String!
#   uri: String!
# }

type Ticket @entity(immutable: true) {
  id: Bytes!
  transactionHash: Bytes!
  timestamp_s: BigInt!
  owner: Bytes!
  ticketShop: Bytes!
  ticketTypeIndex: BigInt!
  ticketId: BigInt!
  ticketName: String!
  ticketPrice: BigInt!

  erc20TokenAddress: Bytes
  nftAddress: Bytes
}

# type TicketShop @entity(immutable: true) {
#   id: Bytes!
#   owner: Bytes! # address
#   ticketShop: Bytes! # address
#   ticketMetadata_id: String! # string
#   ticketMetadata_name: String! # string
#   ticketMetadata_description: String! # string
#   ticketMetadata_uri: String! # string
#   ticketMetadata_dates: [BigInt!]! # uint256[2]
#   ticketMetadata_location_name: String! # string
#   ticketMetadata_location_uri: String! # string
#   ticketMetadata_pricing: [TicketPricing]! # tuple[]
# }
